# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_YixZSHvvOJKRn99NXMdIaE9K8rphtMN
"""

# Type here the Big Loop
import random
x=random.randint(0,100)
print(x)
i=0
guesses= [] 
while(True):
    z=int(input("please enter your guess"))
    while(z<1 or z>100):
        print("out of bounds")
        break;
    else:
        print("in bounds")
        if z in range(x-10,x+10):
            print(' you are closer to target ')
            if z!=x or z==x: 
                i+=1
                guesses.append(i)
                if z==x:
                  print('Wow, you\'ve guessed Correctly this time') 
                  print('You have guessed it in '+ str(i) +' times')              
        elif z in reversed(range(x-10)) or z in range(x+10,x+1000): 
            print(' you are far from the target ')
            if z!=x or z==x: 
                i+=1
                guesses.append(i)
                if z==x:
                  print('Wow, you\'ve guessed Correctly this time') 
                  print('You have guessed it in '+ str(i) +' times')